apiVersion: v1
kind: Pod
metadata:
  labels:
    run: simple-web-app
    app: simple-web-app
  name: simple-web-app-1
spec:
  containers:
    - image: docker.io/library/simple-webapp:2
      name: simple-web-app-1
  initContainers:
    - name: db-initilization
      image: docker.io/library/init:1
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: simple-web-app
    app: simple-web-app
  name: simple-web-app-2
spec:
  containers:
    - image: docker.io/library/simple-webapp:2
      name: simple-web-app-2
  initContainers:
    - name: db-initilization
      image: docker.io/library/init:1
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: simple-web-app
    app: simple-web-app
  name: simple-web-app-3
spec:
  containers:
    - image: docker.io/library/simple-webapp:2
      name: simple-web-app-3
  initContainers:
    - name: db-initilization
      image: docker.io/library/init:1